### ISSUE TITLE
ERROR IndexError : list index out of range

### ISSUE THREAD

**Issue by Flecky13** [Gentleman1983/ginlong_solis_api_connector#24]
![grafik](https://github.com/Gentleman1983/ginlong_solis_api_connector/assets/57505680/0e4dddc7-78e5-449e-9c2e-97abada3ea12)

Hello,
I get the error message shown in the screenshot.

I tried to narrow down the cause but unfortunately my experience with Python is still low.

I would be grateful for support

**Comment by Gentleman1983** [comment]
Hi, @Flecky13!

Thanks for your issue. We'll have a look on that issue. I'll hope @TobiO79 or me will detect some issues until tomorrow. Otherwise we'll only be able to continue investigation in the next week because being away over the weekend.

Can you provide some information about your configuration? Thx.

**Comment by Flecky13** [comment]
Hi @Gentleman1983 
Thanks for taking care of it, no stress.

I use the whole thing in a Raspi on which Docker is running, in the Dockerfile I have made the Cloud_API information, and use MQTT as output

the data should come from a Solis RHI-3P(5-10)K-HVES-5G connected to the cloud via S3-wifi-ST

I'll give you the complete output when LOG info is set to DEBUG
[DEBUG_Output.log](https://github.com/Gentleman1983/ginlong_solis_api_connector/files/11749467/DEBUG_Output.log)

**Comment by TobiO79** [comment]
@Flecky13 Since when is your inverter active? Longer than two month?

**Comment by Flecky13** [comment]
hi @TobiO79 
aktivated first time at 13.05.2023

**Comment by Gentleman1983** [comment]
@TobiO79 have a look on fix for safe calculation of last months energy generation. This should be the only logical location, where the index out of bounds exception may have happened.

As @Flecky13 currently wrote the List of the past months should only have a single entry and the call for `dict_year[-2]` on write to influx db may have resulted in that exception.

@Flecky13 
@TobiO79 and me had a call for some minutes and had a look on the data import from our solis cloud accounts. They are online since summer 2021. So there had been no issue on import of data for too little time past. Tobi had verified, that the data export to MQTT should work fine. Almost all other calls (except the inverter id) should be safe - as that all ids or indices should be provided by solis cloud data specification.
If you want to have a try yourself, you may have a look to the branch linked to this issue.

**Comment by Gentleman1983** [comment]
@all-contributors
Please add @Flecky13 for bug.

**Comment by Flecky13** [comment]
Sorry but the error persists.

I sent you an email with access data so you can test it live

**Comment by Gentleman1983** [comment]
Thanks. We'll have a look tomorrow evening.

**Comment by Gentleman1983** [comment]
hi @Flecky13 !

We had a look on your `Dockerfile`. We identified the issue. Your value `SOLIS_CLOUD_API_INVERTER_ID` was wrong. Using the ID=`0` we had no issue pulling the data. 

We'll have a look to provide better debug information on calling non existing inverter ids from the api. The error provided is not optimal.

@TobiO79 @Gentleman1983 
Reminder: Add useful error in case of mismatch of `SOLIS_CLOUD_API_INVERTER_ID` to existing Inverter IDs

**Comment by Flecky13** [comment]
Really cool, thanks.

it works, I get the values via MQTT.

but immediately announce an improvement proposal on the topic MQTT Topic. I write you a new improvement proposal. :-D

**Comment by Gentleman1983** [comment]
That's great.

@TobiO79 you may review the new PR.

**Comment by TobiO79** [comment]
Number of Inverters is not calculatet correctly

**Comment by TobiO79** [comment]
Check is still not correct.
ERROR Your 'SOLIS_CLOUD_API_INVERTER_ID' (0) is larger than or equal to the available number of inverters (0). Please select a value between '0' and '-1'.

The ID may be equal, but may not be greater than the existing inverters.
